export const GO_NTH_PAGE = 'GO_NTH_PAGE'
export const UPDATE_PAGE_INFO = 'UPDATE_PAGE_INFO'
export const UPDATE_SEARCH_RESULT_HISTORY =
  'UPDATE_SEARCH_RESULT_HISTORY'
export const UPDATE_CURRENT_SEARCH_RESULT =
  'UPDATE_CURRENT_SEARCH_RESULT'
export const OPEN_LOADER = 'OPEN_LOADER'
export const CLOSE_LOADER = 'CLOSE_LOADER'
